##服务端口配置
server: 
  port: 9411
##应用配置
spring:
  application:
    name: zipkin-server
  zipkin:  
    enabled: true
##eureka配置
eureka: 
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/  #注册中心地址
    registry-fetch-interval-seconds: 5
  instance:
    hostname: localhost
    instanceId: http://localhost:9411
    lease-renewal-interval-in-seconds: 5      # 心跳时间，即服务续约间隔时间（缺省为30s）
    lease-expiration-duration-in-seconds: 15  # 发呆时间，即服务续约到期时间（缺省为90s）