##配置访问eureka注册中心地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
    ##健康检查
    healthcheck:  
      enabled: true
##配置引用名称
spring:
  application:
    name: gateway
##配置服务启动端口
server:
  port: 8083
  
##配置路由规则
zuul:
  routes:
    demo:
      path: /demo/**
      serviceId: service0
    demo1:
      path: /demo1/**
      serviceId: service0