server:
  port: 7020
eureka:
  client:
    service-url:  
      defaultZone: http://localhost:8080/eureka/  #注册中心地址
    registry-fetch-interval-seconds: 5
  instance:
    lease-renewal-interval-in-seconds: 10
spring:
  application:
    name: 'spring-boot-admin'
  cloud:
    config:
      enabled: false
  boot:
    admin:
      routes:
        endpoints: env,metrics,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream
      turbine:
        clusters: default
        location: turbine
